# Generated by Django 5.2 on 2025-09-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('is_completed', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5)),
                ('date', models.DateField()),
                ('categories', models.ManyToManyField(to='categories.categories')),
            ],
        ),
    ]
